### ISSUE TITLE
you should do a binary release. and then more binary releases. people want something they can click on and install. also get pcbox in AUR, debian, alpine etc. maybe port to the BSDs too and get ports tree patches there

### ISSUE THREAD

**Issue by githubisnonfree** [PCBox/PCBox#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by githubisnonfree** [comment]
also, your website sucks

get a logo, and make something that's nice. maybe show some screenshots of windows 98 running at 2 frames per second

could even do a testimonials page!

**Comment by githubisnonfree** [comment]
yeah then with all this you'll get more users, and probably attract devs too

then just like. spam it to everyone, get the word out that you exist

your project is awesome, and people need to see it

**Comment by Torinde** [comment]
Related #55

**Comment by KoghaandSooga** [comment]
> Related #55

Nothing there shows a exe file.

**Comment by CreamGravy** [comment]
> Related #55

Please consider releasing. Artifacts are currently not available to those who do not have an account on Github.

**Comment by fuel-pcbox** [comment]
> > Related #55
> 
> Please consider releasing. Artifacts are currently not available to those who do not have an account on Github.

I'll release a stable build once there are no known bugs with the Pentium 3 emulation. I wouldn't want one of my headlining features to be broken after all :P

Other than that, I have no options, as I do not have the resources to host a build server like 86Box does. My ISP also doesn't allow me to host public-facing servers from home, so that's another option that won't work. Sorry :/
